# Generated by Django 4.1 on 2022-08-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
