# Generated by Django 4.1 on 2022-08-11 18:18

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_delete_param_movie_movie_movie_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_length',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(null=True, upload_to='movies/movie/%y%m%d', validators=[movie.models.validate_file_extension]),
        ),
    ]
