# Generated by Django 4.1 on 2022-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_movie_length_movie_length_alter_movie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
