# Generated by Django 4.1 on 2022-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.TextField(choices=[]),
        ),
    ]
