# Generated by Django 4.1 on 2022-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_status_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.TextField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Documentry', 'Documentry'), ('Science', 'Science'), ('Technology', 'Technology'), ('Biography', 'Biography')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
