# Generated by Django 4.1 on 2022-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='movies/thumbnails/%y%m%d'),
        ),
    ]
